[package]
name = "exercise_004_control_flow"
version = "0.1.0"
authors = ["Joe Abell <joe.abell@isotoma.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
